import type { Metadata } from "next";
import "./globals.css";
import { Provider } from "@/components/ui/provider";
import { Box, VStack } from "@chakra-ui/react";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
<html>
      <body style={{ height: "100vh",  overflow: "hidden" }}>
        <Provider >
          <Box width='100%' height="full">
          {children}
          </Box>
        </Provider>
      </body>
    </html>
  );
}
